import {XItem} from "../helpers/bundler.js";
export default class XElem implements DOMElement {
	private _xItem;
	private _parent;
	private _isParented;
	private _renderPromise?;
	constructor(xItem: XItem);
	get xItem(): XItem;
	get elem(): HTMLElement;
	get parent(): XItem | XScope;
	get isRendered(): boolean;
	get isParented(): boolean;
	get _x(): number;
	get _y(): number;
	get _pos(): point;
	get _rotation(): number;
	get _scale(): number;
	get pos(): point;
	get x(): number;
	get y(): number;
	get rotation(): number;
	get scale(): number;
	get height(): number;
	get width(): number;
	get size(): number;
	get radius(): number | false;
	getLocalPosData(ofItem: XItem, globalPoint?: point): pointFull;
	asyncRender(): Promise<any>;
	whenRendered(func: anyFunc): any;
	adopt(xParent: XItem, isRetainingPosition?: boolean): void;
	to(vars: gsap.TweenVars): any;
	from(vars: gsap.TweenVars): any;
	fromTo(fromVars: gsap.TweenVars, toVars: gsap.TweenVars): any;
	set(vars: gsap.TweenVars): any;
}
